name: Java CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Compile Java sources
        run: |
          mkdir -p build
          javac -d build src/*.java

      - name: Run main class (Exo1 by défaut)
        run: java -cp build Exo1
